services:
    wg-easy:
        image: ghcr.io/wg-easy/wg-easy:15.1
        container_name: wg-easy
        network_mode: host          # Usa directamente la red del VPS
        restart: unless-stopped
        environment:
            - INIT_ENABLED=true
            - INIT_USERNAME=${WG_UI_USERNAME}
            - INIT_PASSWORD=${WG_UI_PASSWORD}
            - INIT_HOST=${WG_HOST}
            - INIT_PORT=${WG_PORT:-51820}
            - INIT_DNS=${WG_DNS:-1.1.1.1,8.8.8.8}
            - INIT_IPV4_CIDR=10.8.0.0/24
            - INIT_IPV6_CIDR=2001:db8::/32
            - PORT=${WG_UI_PORT:-51821}  # Interfaz web
            - HOST=0.0.0.0
            - INSECURE=false
            - DISABLE_IPV6=false
        volumes:
            - ${CONFIG_DIR}:/etc/wireguard
            - /lib/modules:/lib/modules:ro
        cap_add:
            - NET_ADMIN
            - SYS_MODULE

    caddy:
        image: caddy:2.8
        container_name: caddy
        network_mode: host          # Usa directamente la red del VPS
        restart: unless-stopped
        depends_on:
            - wg-easy
        environment:
            DOMAIN: ${WG_HOST}
            EMAIL: ${CADDY_EMAIL}
            WG_UI_PORT: ${WG_UI_PORT}
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile
            - ./caddy_data:/data
            - ./caddy_config:/config
