services:
    wg-easy:
        image: ghcr.io/wg-easy/wg-easy:15
        container_name: wg-easy
        network_mode: host          # Usa directamente la red del VPS
        restart: unless-stopped
        environment:
            - INIT_ENABLED=true
            - INIT_USERNAME=${WG_UI_USERNAME}
            - INIT_PASSWORD=${WG_UI_PASSWORD}
            - INIT_HOST=${WG_HOST}
            - INIT_PORT=${WG_PORT:-51820}
            - INIT_DNS=${WG_DNS:-1.1.1.1,8.8.8.8}
            - INIT_IPV4_CIDR=10.8.0.0/24
            - INIT_IPV6_CIDR=2001:db8::/32
            - PORT=${WG_UI_PORT:-51821}  # Interfaz web
            - HOST=0.0.0.0
            - INSECURE=false
            - DISABLE_IPV6=true
        volumes:
            - ${CONFIG_DIR}:/etc/wireguard
            - /lib/modules:/lib/modules:ro
        cap_add:
            - NET_ADMIN
            - SYS_MODULE

    registry-ui:
        image: joxit/docker-registry-ui:latest
        container_name: registry-ui
        restart: always
        ports:
            - "127.0.0.1:8081:80"  
        environment:
            - SINGLE_REGISTRY=true
            - REGISTRY_TITLE=AlexSoft Hub
            - DELETE_IMAGES=true
            - NGINX_PROXY_PASS_URL=http://docker-registry:5000
            - SHOW_CONTENT_DIGEST=true

    docker-registry:
        image: registry:3
        container_name: docker-registry
        restart: always
        environment:
            REGISTRY_STORAGE_DELETE_ENABLED: "true"
        volumes:
            - ./registry/data:/var/lib/registry
    
    caddy:
        image: caddy:2.8
        container_name: caddy
        restart: unless-stopped
        network_mode: host          # Usa directamente la red del VPS
        environment:
            - WG_HOST=${WG_HOST}
            - CADDY_EMAIL=${CADDY_EMAIL}
            - HUB_HOST=${HUB_HOST}
            - HUB_USER=${HUB_USER}
            - HUB_PASSWORD_HASH=${HUB_PASSWORD_HASH}
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile
            - ./caddy_data:/data
            - ./caddy_config:/config